### ISSUE TITLE
请问有python实现吗

### ISSUE THREAD

**Issue by anson2416** [Larry850806/ptt-daily-beauty#1]
谢谢回答。

**Comment by LarryLuTW** [comment]
沒有欸，目前這個專案都是用 Go，但語言只是工具，你有心的話也可以改寫出一個 Python 版的

或是你想學學 Go 的話我很推薦官方的 [A Tour Of Go](https://tour.golang.org/welcome/1)，學過 Python 的話應該稍微看一下就會寫了
